name: clean_arch_sample
description: Clean Arch Sample.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #arch
  get_it: ^7.2.0
  flutter_bloc: ^8.1.1
  auto_route: ^5.0.1
  freezed_annotation: ^2.1.0
  path_provider: ^2.0.11  #used with dio_cache_interceptor
  encrypt: ^5.0.1 #used with dio_cache_interceptor
  form_field_validator: ^1.1.0
  logger: ^1.1.0


  #network
  dio: ^4.0.6
  pretty_dio_logger: ^1.1.1
  retry: ^3.1.0
  dio_cache_interceptor: ^3.3.0
  dio_cache_interceptor_hive_store: ^3.2.0
  json_annotation: ^4.6.0
  internet_connection_checker: ^0.0.1+4
  connectivity_plus: ^2.3.6+1

  #local
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^1.1.3
  shared_preferences: ^2.0.15
  flutter_secure_storage: ^6.0.0  #used with dio_cache_interceptor

  #presentation
  flutter_screenutil: 5.5.3+2
  cupertino_icons: ^1.0.5
  loader_overlay: ^2.0.10
  adaptive_dialog: ^1.8.0
  fluttertoast: ^8.0.9


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  auto_route_generator: ^5.0.1
  build_runner: ^2.2.0
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1

flutter:
  uses-material-design: true
  generate: true
