name: clean_arch_sample
description: Clean Arch Sample.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #arch
  get_it: ^7.2.0
  flutter_bloc: ^8.1.2
  auto_route: ^6.0.0+1
  freezed_annotation: ^2.2.0
  path_provider: ^2.0.13  #used with dio_cache_interceptor
  encrypt: ^5.0.1 #used with dio_cache_interceptor
  form_field_validator: ^1.1.0
  logger: ^1.3.0
  theme_tailor_annotation: ^1.0.3

  #network
  dio: ^5.0.3
  pretty_dio_logger: ^1.3.1
  retry: ^3.1.0
  dio_cache_interceptor: ^3.4.0
  dio_cache_interceptor_hive_store: ^3.2.1
  json_annotation: ^4.8.0
  internet_connection_checker: ^1.0.0+1
  connectivity_plus: ^3.0.3

  #local
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0
  shared_preferences: ^2.0.18
  flutter_secure_storage: ^8.0.0  #used with dio_cache_interceptor

  #presentation
  flutter_screenutil: ^5.7.0
  cupertino_icons: ^1.0.5
  loader_overlay: ^2.1.0
  adaptive_dialog: ^1.8.2
  fluttertoast: ^8.2.1
  flutter_native_splash: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  auto_route_generator: ^6.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  dart_code_metrics: ^5.6.0
  theme_tailor: ^1.0.8

flutter:
  uses-material-design: true
  generate: true
